# Default values for pac-annotations-mapper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  isResilient: "false"
eksCluster: false
replicaCount: 2
image:
  repository: coco/pac-annotations-mapper
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 45Mi
  limits:
    memory: 256Mi


